#!/usr/bin/env python3
"""kai ruling-capture: the conversation-only-ruling control (R19).

The handoff hooks see Git. A ruling that exists only in conversation leaves
no trace in Git, so they cannot see it -- the blind spot named in
handoff-hook.sh, and the mechanism behind the 2026-09-25 admission that a
cold-started thread reversed (D387). This hook closes it from the other
side: it watches the operator's prompts, which is where rulings arrive.

  prompt  (UserPromptSubmit) FLAG a prompt that may carry a ruling or
          direction; keep its exact text in the clone-local store; tell
          Claude, in context, to bank it before acting. Every prompt also
          re-announces whatever is still OUTSTANDING.
  stop    (Stop) BLOCK the end of a turn while anything is OUTSTANDING.
          Inside its own continuation (stop_hook_active) it blocks again
          only if the outstanding set changed, so it cannot loop.
  report  (SessionStart) list OUTSTANDING and WAIVED. Survives compaction
          and resume because the store is in the clone, not in context.
  status  the same, by hand.
  waive ID REASON   record that a flagged prompt carries no ruling. The
          reason is kept and shown at every session start: a waiver is a
          visible decision, never a silent one.
  selftest          known-positive / known-negative cases, end to end in a
          throwaway repository with a bare remote.

BANKED means: the prompt's text, whitespace-normalised, lies inside one
BEGIN-VERBATIM/END-VERBATIM block of kai-pm/HANDOFF_LOG.md AT THE
UPSTREAM REF (pushed, not merely committed -- "carried forward means
committed and pushed", R19). A prompt under SHORT characters must equal a
whole line or the whole block, because a short text like "I authorise"
occurs inside unrelated prose and would read as banked when it is not
(measured on this session's 146 prompts, 2026-10-07).

OUTSTANDING = FLAGGED - BANKED - WAIVED.

Blind spots, stated: answers given through AskUserQuestion arrive as tool
results, not prompts, and are not seen; the store lives in .git of this
clone, so a destroyed container loses unbanked items with the conversation
itself. Never breaks a session: every internal error exits 0 and is
reported as a HOOK: line. Writes nothing in the work tree.
"""
from __future__ import annotations

import hashlib
import json
import os
import pathlib
import re
import subprocess
import sys
import time

LOG_REL = "kai-pm/HANDOFF_LOG.md"
SHORT = 80
WS = re.compile(r"\s+")
PASTE_TAG = re.compile(r"^[ \t]*</?pasted_content\b[^>\n]*>[ \t]*$", re.M)
BEGIN = re.compile(r"^\s*BEGIN-VERBATIM\s+(\S+)\s*$")
END = re.compile(r"^\s*END-VERBATIM\s+(\S+)\s*$")
TAG_QUOTE = re.compile(r'\[CONVERSATION [^\]\n]*?"([^"\n]*)"\]')

# Machine-generated turns: never a ruling.
WRAPPERS = ("This session is being continued from a previous conversation",
            "<command-name>", "<command-message>", "<local-command-stdout>",
            "<local-command-stderr>", "<task-notification>",
            "Caveat: The messages below were generated by the user")

# Words that carry authority or direct action. Derived from the prompts of
# this session that were banked by hand (2026-09-30 .. 2026-10-07).
STRONG = re.compile(
    r"(?i)\b(?:authori[sz]\w*|approv\w*|ruling|rule[sd]?\b|adjudicat\w*|"
    r"directive|direct(?:ed|s)?\b|verdict|enforce\w*|decision|decide\w*|"
    r"go ahead|go with|proceed\w*|implement\w*|execute|choose|option\s+\w\b|"
    r"cancel\w*|delete|merge|push|commit\b|hold|held|stop|forbid\w*|"
    r"do not|don['’]t|never|must|mandatory|required?|accept(?:ed)?|"
    r"reject\w*|supersed\w*|withdraw\w*|i call on you|priorit\w*|"
    r"from now on|always|instead)\b")
HEADER = re.compile(
    r"(?i)\b(?:kai|dainius|deepseek|gpt)\b\s*(?:→|->|=>|—>|to)\s*\b(?:orion|claude)\b")
LONG = 300  # every Kai/DeepSeek message of the corpus is longer than this


def norm(text: str) -> str:
    return WS.sub(" ", PASTE_TAG.sub("", text or "")).strip()


def classify(text: str):
    """Pure. Returns (flagged: bool, reasons: list[str])."""
    t = (text or "").strip()
    if not t:
        return False, ["empty"]
    for w in WRAPPERS:
        if t.startswith(w):
            return False, ["machine-wrapper"]
    n = norm(t)
    reasons = []
    if HEADER.search(n):
        reasons.append("header")
    if len(n) >= LONG:
        reasons.append(f"long({len(n)})")
    m = STRONG.search(n)
    if m:
        reasons.append(f"keyword({m.group(0).lower()})")
    return bool(reasons), reasons or ["no-marker"]


def pid(text: str) -> str:
    return hashlib.sha256(norm(text).encode("utf-8")).hexdigest()[:16]


# ── banked: verbatim blocks of the log at the upstream ref ─────────────
def verbatim_blocks(log_text: str):
    out, cur, name = [], None, None
    for line in log_text.split("\n"):
        if cur is None:
            m = BEGIN.match(line)
            if m:
                cur, name = [], m.group(1)
        else:
            m = END.match(line)
            if m and m.group(1) == name:
                out.append(cur)
                cur = None
            else:
                cur.append(line)
    return out


def bank_index(log_text: str):
    blocks = [[norm(l) for l in b] for b in verbatim_blocks(log_text)]
    whole = [" ".join(x for x in b if x) for b in blocks]
    lines = {x for b in blocks for x in b if x}
    # A short prompt quoted WHOLE in a [CONVERSATION ..., "..."] tag is a
    # faithful record of it (how short rulings were banked by hand). Whole
    # quote only: a substring of a quote is not a record of the prompt.
    lines |= {norm(q) for q in TAG_QUOTE.findall(log_text) if norm(q)}
    return whole, lines


def is_banked(text: str, index) -> bool:
    whole, lines = index
    n = norm(text)
    if not n:
        return True
    if len(n) < SHORT:
        return n in lines or n in whole
    return any(n in w for w in whole)


def git(root, *args, timeout=20):
    return subprocess.run(["git", "-C", str(root), *args], capture_output=True,
                          text=True, timeout=timeout)


def upstream_ref(root):
    r = git(root, "rev-parse", "--abbrev-ref", "--symbolic-full-name", "@{upstream}")
    if r.returncode == 0 and r.stdout.strip():
        return r.stdout.strip()
    try:
        live = (pathlib.Path(root) / ".claude/handoff-branch").read_text().split()[0]
        return f"origin/{live}"
    except (OSError, IndexError):
        return None


def pushed_log(root):
    """(ref, text) of the handoff log at the upstream ref, or (ref, None)."""
    ref = upstream_ref(root)
    if not ref:
        return None, None
    r = git(root, "show", f"{ref}:{LOG_REL}")
    return ref, (r.stdout if r.returncode == 0 else None)


# ── store: clone-local, outside the work tree ──────────────────────────
def store_dir(root):
    env = os.environ.get("KAI_RULING_STORE")
    if env:
        d = pathlib.Path(env)
    else:
        r = git(root, "rev-parse", "--git-common-dir")
        g = pathlib.Path(r.stdout.strip()) if r.returncode == 0 else None
        if g is None:
            return None
        if not g.is_absolute():
            g = pathlib.Path(root) / g
        d = g / "kai-ruling-capture"
    d.mkdir(parents=True, exist_ok=True)
    return d


def load(d):
    recs = {}
    for p in sorted(d.glob("*.json")):
        try:
            r = json.loads(p.read_text(encoding="utf-8"))
            recs[r["id"]] = r
        except (OSError, ValueError, KeyError):
            continue
    return recs


def save(d, rec):
    p = d / f"{rec['id']}.json"
    tmp = p.with_suffix(".tmp")
    tmp.write_text(json.dumps(rec, ensure_ascii=False, indent=1), encoding="utf-8")
    os.chmod(tmp, 0o600)
    os.replace(tmp, p)


def outstanding(root, d):
    recs = load(d)
    ref, log = pushed_log(root)
    if log is None:
        return recs, ref, None
    idx = bank_index(log)
    out = [r for r in recs.values() if r.get("flagged") and not r.get("waived")
           and not is_banked(r["text"], idx)]
    out.sort(key=lambda r: r.get("utc", ""))
    return recs, ref, out


def describe(r):
    first = norm(r["text"])[:70]
    return f"{r['id']} ({r.get('utc', '?')}, {len(r['text'])} chars, {', '.join(r.get('reasons', []))}): \"{first}…\""


WAIVE = "python3 -B .claude/hooks/ruling_capture.py waive <id> \"<reason>\""


# ── events ─────────────────────────────────────────────────────────────
def on_prompt(root, payload):
    text = payload.get("prompt") or ""
    d = store_dir(root)
    flagged, reasons = classify(text)
    msgs = []
    if flagged:
        i = pid(text)
        recs = load(d)
        if i not in recs:
            save(d, {"id": i, "utc": time.strftime("%Y-%m-%dT%H:%M:%SZ", time.gmtime()),
                     "session": payload.get("session_id"), "flagged": True,
                     "reasons": reasons, "text": text, "waived": None})
    recs, ref, out = outstanding(root, d)
    if out is None:
        msgs.append(f"RULING-CAPTURE: HOOK: the handoff log at the upstream ref ({ref}) "
                    f"could not be read, so BANKED is NOT MEASURED; bank by hand.")
    if flagged:
        i = pid(text)
        if out is not None and all(r["id"] != i for r in out) and not recs[i].get("waived"):
            msgs.append(f"RULING-CAPTURE: this prompt ({i}) is flagged and already BANKED at {ref}.")
        else:
            msgs.append(
                f"RULING-CAPTURE: this prompt is FLAGGED as a possible ruling or direction "
                f"(id {i}; {', '.join(reasons)}). R19: bank it word for word in a "
                f"kai-pm/HANDOFF_LOG.md verbatim block (⚠ UNBANKED until in DECISIONS.md), "
                f"commit and push, BEFORE acting on it. If it carries no ruling: {WAIVE}. "
                f"The Stop hook blocks the end of the turn until one of the two is done.")
    others = [r for r in (out or []) if r["id"] != pid(text)]
    if others:
        msgs.append("RULING-CAPTURE: still OUTSTANDING (flagged, not banked at "
                    f"{ref}, not waived):\n" + "\n".join("  " + describe(r) for r in others))
    if msgs:
        print("\n".join(msgs))
    return 0


def stop_action(out, payload, last_blocked):
    """Pure. ('allow',) or ('block', key)."""
    if not out:
        return ("allow",)
    key = ",".join(sorted(r["id"] for r in out))
    if payload.get("stop_hook_active") and key == last_blocked:
        return ("allow",)
    return ("block", key)


def on_stop(root, payload):
    d = store_dir(root)
    recs, ref, out = outstanding(root, d)
    if out is None:
        return 0
    mk = d / "last-stop-block"
    last = mk.read_text().strip() if mk.is_file() else ""
    act = stop_action(out, payload, last)
    if act[0] == "allow":
        return 0
    mk.write_text(act[1])
    reason = ("RULING-CAPTURE (Stop): flagged prompts are neither BANKED at "
              f"{ref} nor waived:\n" + "\n".join("  " + describe(r) for r in out) +
              "\nBank each word for word in a kai-pm/HANDOFF_LOG.md verbatim block, "
              f"commit and push (R19); or, if it carries no ruling: {WAIVE}. "
              "If neither is possible now, tell the operator in one line why.")
    print(json.dumps({"decision": "block", "reason": reason}))
    return 0


def on_report(root, _payload=None, label="SessionStart"):
    d = store_dir(root)
    recs, ref, out = outstanding(root, d)
    flagged = [r for r in recs.values() if r.get("flagged")]
    waived = [r for r in flagged if r.get("waived")]
    print(f"=== ruling-capture ({label}) — store {d} ===")
    if out is None:
        print(f"HOOK: the handoff log at the upstream ref ({ref}) could not be read — "
              f"BANKED is NOT MEASURED.")
        return 0
    print(f"RULING-CAPTURE: flagged={len(flagged)} banked-at-{ref}="
          f"{len(flagged) - len(waived) - len(out)} waived={len(waived)} "
          f"OUTSTANDING={len(out)} (this clone's store only)")
    for r in out:
        print("  OUTSTANDING " + describe(r))
    for r in sorted(waived, key=lambda r: r.get("utc", "")):
        print(f"  WAIVED {r['id']} — {r['waived']['reason']} ({r['waived']['utc']})")
    if out:
        print("RULING-CAPTURE: bank every OUTSTANDING prompt before other work (R19).")
    return 0


def cmd_waive(root, argv):
    if len(argv) < 2 or len(" ".join(argv[1:]).strip()) < 10:
        print("usage: ruling_capture.py waive ID REASON   (reason of 10+ characters)",
              file=sys.stderr)
        return 2
    d = store_dir(root)
    recs = load(d)
    r = recs.get(argv[0])
    if r is None:
        print(f"no flagged prompt with id {argv[0]}", file=sys.stderr)
        return 2
    r["waived"] = {"utc": time.strftime("%Y-%m-%dT%H:%M:%SZ", time.gmtime()),
                   "reason": " ".join(argv[1:]).strip()}
    save(d, r)
    print(f"WAIVED {r['id']}: {r['waived']['reason']}")
    return 0


# ── selftest ───────────────────────────────────────────────────────────
def selftest():
    import tempfile
    fails, n = [], 0

    def ok(name, cond):
        nonlocal n
        n += 1
        if not cond:
            fails.append(name)

    # classify: known-negatives, then known-positives
    ok("neg wrapper", not classify("This session is being continued from a previous conversation that ran out")[0])
    ok("neg task-notification", not classify("<task-notification>\n<task-id>x</task-id>")[0])
    ok("neg short question", not classify("Is you hook on start still ok ?")[0])
    ok("neg ack", not classify("Continue")[0])
    ok("neg empty", not classify("   ")[0])
    ok("pos authorise", classify("I authorise")[0])
    ok("pos go with", classify("Ok go with B, draft our own")[0])
    ok("pos enforce", classify("Please do all that and enforce")[0])
    ok("pos header", classify("KAI → ORION — HOLD")[0])
    ok("pos long", classify("x " * 200)[0])
    ok("pos implement", classify("Implement to the highest standard")[0])
    # norm / ids
    ok("norm paste tags", norm("<pasted_content id=\"a\">\nhi  there\n</pasted_content id=\"a\">") == "hi there")
    ok("id stable over whitespace", pid("a  b\n") == pid("a b"))
    # banked matcher
    log = ("- ruling ⚠ UNBANKED [CONVERSATION x, \"I authorise it\"] see \"I authorise\" there\n"
           "    BEGIN-VERBATIM R1\n    Please do all that\n    and enforce\n    END-VERBATIM R1\n"
           "    BEGIN-VERBATIM R2\n    " + "long ruling text " * 10 + "\n    END-VERBATIM R2\n")
    idx = bank_index(log)
    ok("short in prose NOT banked", not is_banked("I authorise", idx))
    ok("short whole tag quote banked", is_banked("I authorise it", idx))
    ok("short part of tag quote NOT banked", not is_banked("authorise it", idx))
    ok("short whole line banked", is_banked("Please do all that", idx))
    ok("short partial line NOT banked", not is_banked("do all", idx))
    ok("multi-line short block banked", is_banked("Please do all that\nand enforce", idx))
    ok("long inside block banked", is_banked("long ruling text " * 10, idx))
    ok("long not present NOT banked", not is_banked("other ruling text " * 10, idx))
    ok("unterminated block ignored", bank_index("BEGIN-VERBATIM X\nabc\n") == ([], set()))
    # stop_action: loop guard
    rec = [{"id": "a"}]
    ok("stop allow when none", stop_action([], {}, "") == ("allow",))
    ok("stop block", stop_action(rec, {}, "") == ("block", "a"))
    ok("stop block again on a new turn", stop_action(rec, {}, "a") == ("block", "a"))
    ok("stop no loop in continuation", stop_action(rec, {"stop_hook_active": True}, "a") == ("allow",))
    ok("stop block in continuation if set changed",
       stop_action([{"id": "a"}, {"id": "b"}], {"stop_hook_active": True}, "a")[0] == "block")

    # end to end, real git, bare remote, the hook run as a subprocess
    me = os.path.abspath(__file__)
    with tempfile.TemporaryDirectory() as t:
        t = pathlib.Path(t)
        env = dict(os.environ, GIT_AUTHOR_NAME="t", GIT_AUTHOR_EMAIL="t@t", GIT_COMMITTER_NAME="t",
                   GIT_COMMITTER_EMAIL="t@t", KAI_RULING_STORE=str(t / "store"))
        env.pop("CLAUDE_PROJECT_DIR", None)

        def sh(*a, cwd=None):
            return subprocess.run(a, cwd=cwd, env=env, capture_output=True, text=True)
        sh("git", "init", "-q", "--bare", str(t / "remote.git"))
        sh("git", "init", "-q", "-b", "live", str(t / "w"))
        w = t / "w"
        (w / "kai-pm").mkdir()
        (w / LOG_REL).write_text("# log\n")
        sh("git", "add", "-A", cwd=w)
        sh("git", "commit", "-q", "-m", "c0", cwd=w)
        sh("git", "remote", "add", "origin", str(t / "remote.git"), cwd=w)
        sh("git", "push", "-q", "-u", "origin", "live", cwd=w)

        def hook(event, payload):
            r = subprocess.run([sys.executable, "-B", me, event], cwd=w, env=env,
                               input=json.dumps(payload), capture_output=True, text=True)
            return r.returncode, r.stdout
        ruling = "KAI → ORION — you may proceed with step 2 only."
        rc, o = hook("prompt", {"prompt": ruling, "session_id": "s"})
        ok("e2e prompt flagged", rc == 0 and "FLAGGED" in o)
        rc, o = hook("stop", {"stop_hook_active": False})
        ok("e2e KNOWN-POSITIVE stop blocks", rc == 0 and '"decision": "block"' in o)
        rc, o = hook("stop", {"stop_hook_active": True})
        ok("e2e no loop", rc == 0 and o.strip() == "")
        rc, o = hook("prompt", {"prompt": "Is it ok ?"})
        ok("e2e unflagged prompt re-announces outstanding", "OUTSTANDING" in o and "FLAGGED" not in o)
        # committed but NOT pushed: still outstanding
        with open(w / LOG_REL, "a") as f:
            f.write(f"    BEGIN-VERBATIM K\n    {ruling}\n    END-VERBATIM K\n")
        sh("git", "commit", "-q", "-am", "bank", cwd=w)
        rc, o = hook("stop", {"stop_hook_active": False})
        ok("e2e committed-not-pushed still blocks", '"decision": "block"' in o)
        sh("git", "push", "-q", cwd=w)
        rc, o = hook("stop", {"stop_hook_active": False})
        ok("e2e KNOWN-NEGATIVE banked+pushed allows", rc == 0 and o.strip() == "")
        # waiver path
        hook("prompt", {"prompt": "I authorise you to tidy the scratch dir"})
        rc, o = hook("stop", {})
        ok("e2e second ruling blocks", '"decision": "block"' in o)
        r = subprocess.run([sys.executable, "-B", me, "waive", pid("I authorise you to tidy the scratch dir"), "short"],
                           cwd=w, env=env, capture_output=True, text=True)
        ok("e2e waiver needs a real reason", r.returncode == 2)
        r = subprocess.run([sys.executable, "-B", me, "waive", pid("I authorise you to tidy the scratch dir"),
                            "test fixture, scratch only, no programme effect"],
                           cwd=w, env=env, capture_output=True, text=True)
        ok("e2e waive", r.returncode == 0)
        rc, o = hook("stop", {})
        ok("e2e waived allows", o.strip() == "")
        rc, o = hook("report", {})
        ok("e2e report shows waiver", "WAIVED" in o and "OUTSTANDING=0" in o)
        ok("e2e work tree untouched", sh("git", "status", "--porcelain", cwd=w).stdout == "")
        # unreadable upstream: reported, never blocks
        sh("git", "branch", "--unset-upstream", cwd=w)
        (w / ".claude").mkdir()
        rc, o = hook("prompt", {"prompt": "I authorise X"})
        ok("e2e no upstream: NOT MEASURED, rc 0", rc == 0 and "NOT MEASURED" in o)
        rc, o = hook("stop", {})
        ok("e2e no upstream: stop never blocks", rc == 0 and o.strip() == "")
    print(f"RULING-CAPTURE SELFTEST: {n - len(fails)}/{n} passed" +
          ("" if not fails else "; FAILED: " + "; ".join(fails)))
    return 1 if fails else 0


def main(argv):
    cmd = argv[1] if len(argv) > 1 else ""
    if cmd == "selftest":
        return selftest()
    root = os.environ.get("CLAUDE_PROJECT_DIR") or os.getcwd()
    if cmd == "waive":
        return cmd_waive(root, argv[2:])
    payload = {}
    if cmd in ("prompt", "stop", "report") and not sys.stdin.isatty():
        try:
            raw = sys.stdin.read()
            payload = json.loads(raw) if raw.strip() else {}
        except ValueError:
            payload = {}
    try:
        if cmd == "prompt":
            return on_prompt(root, payload)
        if cmd == "stop":
            return on_stop(root, payload)
        if cmd in ("report", "status"):
            return on_report(root, payload, "SessionStart" if cmd == "report" else "status")
    except Exception as e:  # never break a session
        if cmd != "stop":
            print(f"RULING-CAPTURE: HOOK: internal error {type(e).__name__}: {e} — "
                  f"control NOT run; bank rulings by hand.")
        return 0
    print("usage: ruling_capture.py prompt|stop|report|status|waive ID REASON|selftest",
          file=sys.stderr)
    return 2


if __name__ == "__main__":
    sys.exit(main(sys.argv))
