#!/usr/bin/env python3
"""READER-vs-WRITER known-answer calibration. Answers by construction."""
import pathlib, subprocess, sys, tempfile
sys.path.insert(0,'.'); import genlink as gl
P=F=0; FAILS=[]
def ck(n,c,d=""):
    global P,F
    if c: P+=1
    else: F+=1; FAILS.append(f"{n} :: {d}")

with tempfile.TemporaryDirectory() as d:
    R=pathlib.Path(d)
    (R/"docs").mkdir(parents=True)
    (R/"docs"/"gen.md").write_text("# generated\n")
    (R/"docs"/"hand.md").write_text("# hand written\n")
    (R/"docs"/"quoted.md").write_text("# quoted\n")
    # a genuine WRITER
    (R/"writer.py").write_text(
        'import pathlib\n'
        'pathlib.Path("docs/gen.md").write_text("x")\n')
    # a pure READER of hand.md -- must NOT be a generator
    (R/"reader.py").write_text(
        'import pathlib\n'
        'txt = pathlib.Path("docs/hand.md").read_text()\n'
        'print(txt > "a")\n')          # a `> ` near the mention, deliberately
    # a MENTION beside a redirect -- the exact v2 false positive
    (R/"mentions.sh").write_text(
        '# see docs/quoted.md for detail\n'
        'echo hello > /tmp/other.txt\n')
    # a shell WRITER
    (R/"shellwriter.sh").write_text('echo "# x" > docs/gen.md\n')
    # generated bytecode that mentions everything -- must be EXCLUDED
    (R/"__pycache__").mkdir()
    (R/"__pycache__"/"junk.pyc").write_text(
        'docs/hand.md docs/gen.md write_text >')
    subprocess.run(["git","init","-q"],cwd=R)
    subprocess.run(["git","add","-A"],cwd=R)
    subprocess.run(["git","-c","user.email=c@x","-c","user.name=c",
                    "commit","-q","-m","f"],cwd=R)

    docs=["docs/gen.md","docs/hand.md","docs/quoted.md"]
    g=gl.generators(R,docs)

    ck("W1 python writer IS a generator of gen.md",
       "writer.py" in g["docs/gen.md"], str(g))
    ck("W2 shell writer IS a generator of gen.md",
       "shellwriter.sh" in g["docs/gen.md"], str(g))
    ck("R1 pure READER is NOT a generator of hand.md",
       "reader.py" not in g["docs/hand.md"], str(g))
    ck("R2 hand.md has NO generator at all",
       g["docs/hand.md"] == [], str(g))
    ck("R3 mention beside an unrelated redirect is NOT a generator",
       g["docs/quoted.md"] == [], str(g))
    ck("X1 __pycache__ bytecode excluded from the corpus",
       not any("__pycache__" in f for v in g.values() for f in v), str(g))
    srcs={f for f,_ in gl.source_files(R)}
    ck("X2 exclusion is visible in the corpus listing",
       not any("__pycache__" in s for s in srcs), str(sorted(srcs)))

print(f"READER/WRITER CALIBRATION: {P} passed, {F} failed")
for f in FAILS: print("  FAIL",f)
sys.exit(1 if F else 0)
