#!/usr/bin/env bash
# Generate service and dashboard credentials into the local .env
# (UH tracker E-03; Wave 1 Track A).
#
# .env is gitignored, so the secrets never reach the repository.
# Existing values are preserved unless --force is passed.
#
# KAI_SERVICE_TOKEN   shared secret between services for protected endpoints
# KAI_DASHBOARD_TOKEN the operator's inbound credential for the dashboard
#                     gateway. Deliberately a *different* secret: a
#                     browser-held credential must not also be the one that
#                     authorises service-to-service calls.
set -euo pipefail

ENV_FILE="${ENV_FILE:-.env}"
FORCE="${1:-}"

touch "$ENV_FILE"
wrote_header=0

ensure_token() {
  local name="$1" description="$2"

  if grep -qE "^${name}=.+" "$ENV_FILE"; then
    if [ "$FORCE" != "--force" ]; then
      echo "${name} already set in $ENV_FILE — leaving it alone."
      return 0
    fi
    # Rotating: drop the old line first.
    grep -v "^${name}=" "$ENV_FILE" > "$ENV_FILE.tmp"
    mv "$ENV_FILE.tmp" "$ENV_FILE"
  fi

  local token
  token="$(openssl rand -hex 32)"
  if [ "$wrote_header" -eq 0 ]; then
    printf '\n# Generated by scripts/setup_service_token.sh — do not commit.\n' >> "$ENV_FILE"
    wrote_header=1
  fi
  printf '%s=%s\n' "$name" "$token" >> "$ENV_FILE"
  echo "Wrote ${name} to $ENV_FILE (${#token} chars) — ${description}."
}

ensure_token KAI_SERVICE_TOKEN "shared by every service calling a protected endpoint"
ensure_token KAI_DASHBOARD_TOKEN "the operator's inbound dashboard credential"

if ! grep -qE '^KAI_DASHBOARD_ROLE=' "$ENV_FILE"; then
  # The identity is also the memory subject (KAI-DASH-023): memory reads
  # are scoped to it, and the stack's existing records are under "keeper".
  printf 'KAI_DASHBOARD_IDENTITY=%s\n' "keeper" >> "$ENV_FILE"
  printf 'KAI_DASHBOARD_ROLE=%s\n' "keeper" >> "$ENV_FILE"
  echo "Set KAI_DASHBOARD_IDENTITY=keeper, KAI_DASHBOARD_ROLE=keeper."
fi

chmod 600 "$ENV_FILE" 2>/dev/null || true

if [ "$FORCE" != "--force" ]; then
  echo
  echo "Rotate any of these with: make setup-service-token FORCE=--force"
fi
echo "The dashboard fails closed: without KAI_DASHBOARD_TOKEN it answers 503."
