#!/usr/bin/env bash
# Generate KAI_SERVICE_TOKEN into the local .env (UH tracker E-03).
#
# .env is gitignored, so the secret never reaches the repository.
# Existing values are preserved unless --force is passed.
set -euo pipefail

ENV_FILE="${ENV_FILE:-.env}"
FORCE="${1:-}"

if [ -f "$ENV_FILE" ] && grep -qE '^KAI_SERVICE_TOKEN=.+' "$ENV_FILE"; then
  if [ "$FORCE" != "--force" ]; then
    echo "KAI_SERVICE_TOKEN already set in $ENV_FILE — leaving it alone."
    echo "Rotate it with: make setup-service-token FORCE=--force"
    exit 0
  fi
  # Rotating: drop the old line first.
  grep -v '^KAI_SERVICE_TOKEN=' "$ENV_FILE" > "$ENV_FILE.tmp"
  mv "$ENV_FILE.tmp" "$ENV_FILE"
fi

TOKEN="$(openssl rand -hex 32)"
touch "$ENV_FILE"
printf '\n# Generated by scripts/setup_service_token.sh — do not commit.\n' >> "$ENV_FILE"
printf 'KAI_SERVICE_TOKEN=%s\n' "$TOKEN" >> "$ENV_FILE"

chmod 600 "$ENV_FILE" 2>/dev/null || true

echo "Wrote KAI_SERVICE_TOKEN to $ENV_FILE (${#TOKEN} chars)."
echo "Every service that calls a protected endpoint needs the same value."
